### ISSUE TITLE
/dist/w-json-stream.umd.js is failing to load with "TypeError: undefined is not an object (evaluating '(e=t.exports=hr).Stream=e')"

### ISSUE THREAD

**Issue by disleyland** [yuda-lyu/w-json-stream#1]
none of the example dist files are working as the files w-json-stream.umd.js and w-json-stream.wk.umd.js are not loading properly.  Latest Chrome ( 104.0.5112.101)  and Safari (15.6.1) tested.

**Comment by yuda-lyu** [comment]
Thanks for the notification. I forked from2 and fixed this.

**Comment by disleyland** [comment]
Great ill give it a try now
